### ISSUE TITLE
Can't Install ViGEmClient

### ISSUE THREAD

**Issue by FahrulRPutra** [jangxx/node-ViGEmClient#5]
![image](https://user-images.githubusercontent.com/49786305/96573382-a428d800-1300-11eb-81c9-2aaa10733be9.png)

Tried to install this but this errors keeps occur

**Comment by jangxx** [comment]
I just pushed a fix to the `test` branch. Can you check out the branch and run `npm install` to test if it worked? I can't replicate your issue unfortunately, since the project builds fine with and without the fix for me.

**Comment by FahrulRPutra** [comment]
Im not on the pc yet, but i've tried installed python, installed the driver, still gives an error when installing, it's probably something to do with the file of x360e and dualshock 4. Will try to install it later.

**Comment by jangxx** [comment]
x360ce has nothing to do with this library. The error you are seeing is the compiler complaining about a missing type-cast, which I added in the `test` branch. You might want to try to install the windows build tools if you haven't already (`npm install -g windows-build-tools`), but I would still be happy if you would check if my fix worked so that I can put it into the next release.

**Comment by FahrulRPutra** [comment]
![image](https://user-images.githubusercontent.com/49786305/96670223-6de76900-1391-11eb-9280-e912b4b41785.png)
I tried to npm install -g windows-build-tools
and then npm install vigemclient

still error

trying npm install git://github.com/jangxx/node-ViGEmClient.git#test --save still doesn't work

**Comment by jangxx** [comment]
>I tried to npm install -g windows-build-tools
and then npm install vigemclient

If you look in your screenshot, it clearly says `Could not install Visual Studio Build Tools` in red at the top there. I don't know why the installation fails of course, but maybe the reason is related to your problem with this library.

>trying npm install git://github.com/jangxx/node-ViGEmClient.git#test --save still doesn't work

Could you please provide the error message? It has to be different from your original one, since I changed the specific things the compiler didn't like about it.

Also related to your screenshot: Are you on 32-bit windows? The log above indicates that `node-gyp` is copying the 32-bit version of the vigemclient.dll, which means it thinks you are using a 32-bit system. If you are actually on 64-bit you might want to find out why it's detecting that wrongly and if you are on 32-bit you might want to upgrade to 64-bit, since 32-bit operating systems and software are being phased out for years now. I only included the 32-bit DLLs for completeness sake anyway, and I might drop support for it altogether in the future, since no one uses 32-bit operating systems anymore.

**Comment by FahrulRPutra** [comment]
![image](https://user-images.githubusercontent.com/49786305/96697717-ced96600-13be-11eb-8ff3-a1126ddc9191.png)

I'm on Windows 10 64 Bit

**Comment by FahrulRPutra** [comment]
And i have Visual Studio Community

**Comment by FahrulRPutra** [comment]
Node JS v12.14.0

**Comment by jangxx** [comment]
Apparently you don't have git installed, so you need to install it.

Also you might want to reinstall Node.js and install the 64-bit version. I'm guessing you have the 32-bit version installed and that's the reason for npm copying the 32-bit DLL instead of the 64-bit one. You can run `node -p "process.arch"` to test which version you have installed.

**Comment by FahrulRPutra** [comment]
when i type node -p "process.arch" it responded ia32

**Comment by jangxx** [comment]
That's what I thought. Please install the x64 version of Node and then try installing the `windows-build-tools` again. It might just work without any further changes.

**Comment by FahrulRPutra** [comment]
yeah, i dunno why it used the 32bit, i remember i downloaded the recommended one. I will try to install it again with the new 64Bit

**Comment by FahrulRPutra** [comment]
![image](https://user-images.githubusercontent.com/49786305/96705470-f123b180-13c7-11eb-8e89-4fd66a321086.png)

**Comment by jangxx** [comment]
Looks great, It seems like we don't even need the other fixes.
